### ISSUE TITLE
Naziv klase

### ISSUE THREAD

**Issue by kfurjan** [hermanoff/smartkey#10]
https://github.com/hermanoff/smartkey/blob/183b5765e6ea903ccffc217152c89a05adb154cd/Screens.py#L216

Osobno bih ovo nazvao radije `BottomScreen`

**Comment by hermanoff** [comment]
Mislio sam da ce biti jasno, ali opet da, mozda je dobra praksa pisati puni naziv neceg bez obzira, samo radi lakseg citanja u buducnosti.
