### ISSUE TITLE
String u konstantu

### ISSUE THREAD

**Issue by kfurjan** [hermanoff/smartkey#11]
https://github.com/hermanoff/smartkey/blob/183b5765e6ea903ccffc217152c89a05adb154cd/Screens.py#L295

`"<Button-1>"` ti može biti konstanta pa ćeš izbjeći ponavljanje nekog stringa 3 puta, a taj string sam po sebi je poprilično bitan jer ti definira ponašanje aplikacije.

**Comment by hermanoff** [comment]
O ovome uopce nisam razmisljao. Jos uvijek mi takve stvari nisu postale navika. Popravljeno.
