### ISSUE TITLE
Enum kao bolja alternativa

### ISSUE THREAD

**Issue by kfurjan** [hermanoff/smartkey#12]
https://github.com/hermanoff/smartkey/blob/183b5765e6ea903ccffc217152c89a05adb154cd/Screens.py#L371

Za ovakve provjere je dušu dao `Enum`. `Enum` omogućava lakše popisivanje nekih tipova, u ovom slučaju tipova korisnika. Pomoću `Enum` se mičeš od provjere sa stringom i imaš potpunu eksplicitnu provjeru koja će ti već prije RunTime-a javiti moguću grešku.

Na primjer. U sqlOPS.py:

```python
from enum import Enum
import sqlmodel

database = "Users.db"


class UserType(str, Enum):
    USER = "user"
    ADMIN = "admin"


class User(sqlmodel.SQLModel, table=True):
    id: int = sqlmodel.Field(default=None, primary_key=True)
    first_name: str
    last_name: str
    PIN: int = sqlmodel.Field(unique=True)
    active: bool
    role: UserType

    def __init__(self, **kwargs):
        assert all(kwargs.values()), "All fields must be provided"
        super().__init__(**kwargs)

.
.
.

insert_new_user("Viktor", "Herman", 1337, True, UserType.ADMIN)
```

Kad imaš `UserType` onda to lakše možeš provjeriti u `Screens.py`na sljedeći način:

```python
from sqlOPS import (
    select_by_pin,
    select_by_id,
    update_user,
    insert_new_user,
    delete_user,
    get_all_users,
    UserType
)

.
.
.

    def delete_button_event(self, event: Event) -> None:
        """Delete user from database

        Args:
            event (Event): Left-click on delete button
        """
        user = select_by_pin(self.pin_entry.get())
        if user:
            if user.role != UserType.ADMIN:
                delete_user(user.id)
            if user.role == UserType.ADMIN:
                messagebox.showerror("You can't delete admin user")

        self.refresh_listbox()
```

Ovdje samo napominjen da će ovakav pristup zahtjevati refaktor svog koda koji radi bilo kakvu provjeru role korisnika, itd. pa budi spreman na eventualne greške i debugiranje.

**Comment by hermanoff** [comment]
Super stvar. 
Moram malo poraditi na tome da ne hardkodiram vrijednosti u kodu.

Popravljeno.
