### ISSUE TITLE
Potencijalan None problem

### ISSUE THREAD

**Issue by kfurjan** [hermanoff/smartkey#7]
https://github.com/hermanoff/smartkey/blob/183b5765e6ea903ccffc217152c89a05adb154cd/sqlOPS.py#L65

U ORM alatim `first()` metoda će vratiti entitet ili `None` u slučaju da ga nema što ti može biti problem (bit će `Exception` negdje drugdje u kodu) ako stvarno vrati `None` pa je uvijek dobra praksa prvo provjeriti postoji li zapravo neki podatak.

Također ti trenutno `type hinting` zapravo laže, točno je:

```python
def select_by_pin(pin: int) -> User | None:
    """Return User for a given PIN number

    Args:
        pin (int): PIN number

    Returns:
        User: User object, inherits from sqlmodel.SQLModel
    """
    with sqlmodel.Session(engine) as session:
        query = sqlmodel.select(User).where(User.PIN == pin)
        result = session.exec(query).first()

        return result
```

Ista stvar je i u `select_by_id` funkciji.

**Comment by hermanoff** [comment]
Da, u kodu se i koristi provjera dal se vrati rezultat ili None. Oversight kod pisanja type hintinga.
Ispravljeno.
