### ISSUE TITLE
Star import

### ISSUE THREAD

**Issue by kfurjan** [hermanoff/smartkey#8]
https://github.com/hermanoff/smartkey/blob/183b5765e6ea903ccffc217152c89a05adb154cd/Screens.py#L1

Probaj izbjegavati ovakve importe. Takvi importi mogu dovesti do problema koji se zove `namespace pollution`. Zapravo importaš i stvari koje ne koristiš; neki rule of thumb je da importaš samo ono što zapravo koristiš pa ni nemaš problema (iako nažalost u `tkinter`-u onda moraš dosta toga ručno importati).

**Comment by hermanoff** [comment]
Da, spomenuli smo to nekoliko puta. Bio sam svjestan da nije praksa, ali posto sam koristio samo taj jedan library, mislio sam da nece predstavljati problem.
