### ISSUE TITLE
Konzistentnost u nazivima

### ISSUE THREAD

**Issue by kfurjan** [hermanoff/smartkey#9]
https://github.com/hermanoff/smartkey/blob/183b5765e6ea903ccffc217152c89a05adb154cd/Screens.py#L64

Dobra praksa je držati se jednog jezika. Većina koda/funkcija/klasa ti je na engleskom pa bi bilo dobro da ti je sve na engleskom.

**Comment by hermanoff** [comment]
Da, svjestan sam toga, krenuo sam sve pisati na engleskom, ali kako sam se referencirao na onu grafiku, odlucio sam text u buttonima ostaviti tako kako je sa slike. Onda mi je bilo logicno staviti i nazive funkcije prema textu. Popravljeno.
